### ISSUE TITLE
Loading a pdf results in a StopIteration error

### ISSUE THREAD

**Issue by charlescearl** [explosion/spacy-layout#1]
Running spacy-layout on a Apple M3 Pro with 36GB memory. 
Python version 3.11.7

The following code is invoked in a python Jupyter notebook:

```
import spacy
from spacy_layout import spaCyLayout

nlp = spacy.blank("en")
layout = spaCyLayout(nlp)
doc = layout("a4b3a1f45daf416a950584c918f0a007.pdf")
```

Where `a4b3a1f45daf416a950584c918f0a007.pdf` is a 33 page 1.6M pdf containing text and pictures and tables.

The error

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[15], line 1
----> 1 doc = layout("a4b3a1f45daf416a950584c918f0a007.pdf")

File [~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/spacy_layout/layout.py:36](http://localhost:8889/lab/tree/~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/spacy_layout/layout.py#line=35), in spaCyLayout.__call__(self, path)
     34 def __call__(self, path: str | Path) -> Doc:
     35     """Call parser on a path to create a spaCy Doc object."""
---> 36     result = self.converter.convert(path)
     37     inputs = []
     38     for item in result.document.texts:

File [~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/pydantic/validate_call_decorator.py:60](http://localhost:8889/lab/tree/~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/pydantic/validate_call_decorator.py#line=59), in validate_call.<locals>.validate.<locals>.wrapper_function(*args, **kwargs)
     58 @functools.wraps(function)
     59 def wrapper_function(*args, **kwargs):
---> 60     return validate_call_wrapper(*args, **kwargs)

File [~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py:96](http://localhost:8889/lab/tree/~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py#line=95), in ValidateCallWrapper.__call__(self, *args, **kwargs)
     95 def __call__(self, *args: Any, **kwargs: Any) -> Any:
---> 96     res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
     97     if self.__return_pydantic_validator__:
     98         return self.__return_pydantic_validator__(res)

File [~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/docling/document_converter.py:161](http://localhost:8889/lab/tree/~/github/spacy-layout-exploration/.venv/lib/python3.11/site-packages/docling/document_converter.py#line=160), in DocumentConverter.convert(self, source, raises_on_error, max_num_pages, max_file_size)
    146 @validate_call(config=ConfigDict(strict=True))
    147 def convert(
    148     self,
   (...)
    152     max_file_size: int = sys.maxsize,
    153 ) -> ConversionResult:
    155     all_res = self.convert_all(
    156         source=[source],
    157         raises_on_error=raises_on_error,
    158         max_num_pages=max_num_pages,
    159         max_file_size=max_file_size,
    160     )
--> 161     return next(all_res)

StopIteration:
```

**Comment by ines** [comment]
Thanks for trying it out! This looks like it's triggered by [Docling](https://github.com/DS4SD/docling) so if the following causes the same issue, maybe you could raise it on their tracker?

```python
from docling.document_converter import DocumentConverter

converter = DocumentConverter()
result = converter.convert("a4b3a1f45daf416a950584c918f0a007.pdf")
```

**Comment by charlescearl** [comment]
> so if the following causes the same issue, maybe you could raise it on their tracker?

Thanks @ines. I'm getting the same error. I will raise it with them.

**Comment by charlescearl** [comment]
An update. In version 2.10
```
 + docling==2.10.0
 + docling-core==2.9.0
 + docling-ibm-models==2.0.8
 + docling-parse==3.0.0
```
the following error is returned:

```
>>> result = converter.convert("a4b3a1f45daf416a950584c918f0a007.pdf")
Input document a4b3a1f45daf416a950584c918f0a007.pdf does not match any allowed format.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 38, in wrapper_function
    return wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 111, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/docling/document_converter.py", line 172, in convert
    return next(all_res)
           ^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/docling/document_converter.py", line 193, in convert_all
    for conv_res in conv_res_iter:
  File ".venv/lib/python3.12/site-packages/docling/document_converter.py", line 228, in _convert
    for item in map(
  File ".venv/lib/python3.12/site-packages/docling/document_converter.py", line 273, in _process_document
    raise ConversionError(error_message)
docling.exceptions.ConversionError: File format not allowed: a4b3a1f45daf416a950584c918f0a007.pdf
```
